-- ============================================================
-- CANADA — base villes (miroir de us_cities) + réutilisation de city_guides
-- À exécuter dans le SQL editor de Supabase.
--
-- Principe : même structure que la base US pour que tout le pipeline de contenu
-- unique (SEO + guides enrichis) se transpose à l'identique. On ne remplit pas
-- tout : on a surtout besoin de la géo + des "lieux d'intérêt" pour générer du
-- contenu localement pertinent (police, transports, aéroports, quartiers).
-- ============================================================

-- 1) TABLE VILLES -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS ca_cities (
  id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  province_id      text        NOT NULL,          -- code ISO 2 lettres : "ON","QC","BC"…
  province_name    text        NOT NULL,          -- "Ontario","Quebec"…
  city             text        NOT NULL,          -- nom affiché : "Montréal"
  city_ascii       text        NOT NULL,          -- sans accents/minuscule pour slug : "montreal"
  lat              double precision,
  lng              double precision,
  population       integer,
  density          double precision,
  timezone         text,                          -- "America/Toronto"…
  -- SEO (comme us_cities) : remplis par ville, générés puis validés à la main
  static_title     text,
  static_content   text,
  -- Photo (même pipeline Pexels que côté US)
  image_url        text,
  image_alt        text,
  photographer     text,
  image_source_url text,
  created_at       timestamptz NOT NULL DEFAULT now(),
  UNIQUE (province_id, city_ascii)
);

CREATE INDEX IF NOT EXISTS idx_ca_cities_prov ON ca_cities (province_id);
ALTER TABLE ca_cities ENABLE ROW LEVEL SECURITY;

-- 2) LIEUX D'INTÉRÊT (POIs) — matière première du contenu unique -------------
-- Sert à générer des guides localement vrais (station de métro, poste de police,
-- aéroport, hub touristique…). Un enregistrement = un point d'intérêt rattaché à une ville.
CREATE TABLE IF NOT EXISTS ca_city_pois (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  province_id   text NOT NULL,                    -- "ON"
  city_ascii    text NOT NULL,                    -- "toronto"
  kind          text NOT NULL,                    -- 'police' | 'transit' | 'airport' | 'venue' | 'neighborhood' | 'university' | 'other'
  name          text NOT NULL,                    -- "Toronto Police Service — 51 Division"
  detail        text,                             -- adresse, ligne de métro, terminal, particularité
  url           text,                             -- page officielle lost & found si dispo
  lat           double precision,
  lng           double precision,
  created_at    timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_ca_pois_city ON ca_city_pois (province_id, city_ascii, kind);
ALTER TABLE ca_city_pois ENABLE ROW LEVEL SECURITY;

-- 3) GUIDES ENRICHIS — on RÉUTILISE la table city_guides existante -----------
-- Pas de nouvelle table : city_guides est déjà clé (state_id, city_slug). Comme
-- aucun code de province canadienne ne collisionne avec un État US, on stocke le
-- code province dans state_id. Le composant components/CityGuide.tsx les rend tel quel.
--   INSERT INTO city_guides (state_id, city_slug, guide, status)
--   VALUES ('ON','toronto', '{...CityGuide JSON...}'::jsonb, 'draft');

-- ============================================================
-- SEED — villes majeures (à compléter par l'import long-tail, voir bas de fichier)
-- Population = ville-centre approx. (à affiner depuis le dataset). tz = fuseau IANA.
-- ============================================================
INSERT INTO ca_cities (province_id, province_name, city, city_ascii, lat, lng, population, timezone) VALUES
  ('ON','Ontario','Toronto','toronto',43.6532,-79.3832,2794356,'America/Toronto'),
  ('ON','Ontario','Ottawa','ottawa',45.4215,-75.6972,1017449,'America/Toronto'),
  ('ON','Ontario','Mississauga','mississauga',43.5890,-79.6441,717961,'America/Toronto'),
  ('ON','Ontario','Brampton','brampton',43.7315,-79.7624,656480,'America/Toronto'),
  ('ON','Ontario','Hamilton','hamilton',43.2557,-79.8711,569353,'America/Toronto'),
  ('ON','Ontario','London','london',42.9849,-81.2453,422324,'America/Toronto'),
  ('ON','Ontario','Kitchener','kitchener',43.4516,-80.4925,256885,'America/Toronto'),
  ('ON','Ontario','Windsor','windsor',42.3149,-83.0364,229660,'America/Toronto'),
  ('QC','Quebec','Montréal','montreal',45.5019,-73.5674,1762949,'America/Toronto'),
  ('QC','Quebec','Québec City','quebec-city',46.8139,-71.2080,549459,'America/Toronto'),
  ('QC','Quebec','Laval','laval',45.6066,-73.7124,438366,'America/Toronto'),
  ('QC','Quebec','Gatineau','gatineau',45.4765,-75.7013,291041,'America/Toronto'),
  ('QC','Quebec','Longueuil','longueuil',45.5312,-73.5182,254483,'America/Toronto'),
  ('QC','Quebec','Sherbrooke','sherbrooke',45.4042,-71.8929,172950,'America/Toronto'),
  ('QC','Quebec','Trois-Rivières','trois-rivieres',46.3432,-72.5432,139163,'America/Toronto'),
  ('BC','British Columbia','Vancouver','vancouver',49.2827,-123.1207,662248,'America/Vancouver'),
  ('BC','British Columbia','Surrey','surrey',49.1913,-122.8490,568322,'America/Vancouver'),
  ('BC','British Columbia','Burnaby','burnaby',49.2488,-122.9805,249125,'America/Vancouver'),
  ('BC','British Columbia','Richmond','richmond',49.1666,-123.1336,209937,'America/Vancouver'),
  ('BC','British Columbia','Victoria','victoria',48.4284,-123.3656,91867,'America/Vancouver'),
  ('BC','British Columbia','Kelowna','kelowna',49.8880,-119.4960,144576,'America/Vancouver'),
  ('AB','Alberta','Calgary','calgary',51.0447,-114.0719,1306784,'America/Edmonton'),
  ('AB','Alberta','Edmonton','edmonton',53.5461,-113.4938,1010899,'America/Edmonton'),
  ('AB','Alberta','Red Deer','red-deer',52.2681,-113.8112,100844,'America/Edmonton'),
  ('AB','Alberta','Lethbridge','lethbridge',49.6935,-112.8418,98406,'America/Edmonton'),
  ('MB','Manitoba','Winnipeg','winnipeg',49.8951,-97.1384,749607,'America/Winnipeg'),
  ('SK','Saskatchewan','Saskatoon','saskatoon',52.1332,-106.6700,266141,'America/Regina'),
  ('SK','Saskatchewan','Regina','regina',50.4452,-104.6189,226404,'America/Regina'),
  ('NS','Nova Scotia','Halifax','halifax',44.6488,-63.5752,439819,'America/Halifax'),
  ('NB','New Brunswick','Moncton','moncton',46.0878,-64.7782,79470,'America/Halifax'),
  ('NB','New Brunswick','Saint John','saint-john',45.2733,-66.0633,69895,'America/Halifax'),
  ('NB','New Brunswick','Fredericton','fredericton',45.9636,-66.6431,63116,'America/Halifax'),
  ('NL','Newfoundland and Labrador','St. John''s','st-johns',47.5615,-52.7126,110525,'America/St_Johns'),
  ('PE','Prince Edward Island','Charlottetown','charlottetown',46.2382,-63.1311,38809,'America/Halifax'),
  ('YT','Yukon','Whitehorse','whitehorse',60.7212,-135.0568,28201,'America/Whitehorse'),
  ('NT','Northwest Territories','Yellowknife','yellowknife',62.4540,-114.3718,20340,'America/Yellowknife'),
  ('NU','Nunavut','Iqaluit','iqaluit',63.7467,-68.5170,7740,'America/Iqaluit')
ON CONFLICT (province_id, city_ascii) DO NOTHING;

-- Exemples SEO localisés (title + meta) pour les villes phares -----------------
UPDATE ca_cities SET
  static_title   = 'Lost & Found in Toronto: Report a Lost Item',
  static_content = 'Lost something in Toronto? Report it in minutes and we route it to the right Toronto Police division, the TTC, GO Transit, rideshare and Pearson (YYZ) lost & found, plus local groups.'
WHERE province_id = 'ON' AND city_ascii = 'toronto';

UPDATE ca_cities SET
  static_title   = 'Lost & Found in Montréal: Report a Lost Item',
  static_content = 'Lost something in Montréal? Report it in minutes and we route it to the right SPVM station, the STM (métro/bus), taxi/rideshare and Montréal-Trudeau (YUL) lost & found, plus local groups.'
WHERE province_id = 'QC' AND city_ascii = 'montreal';

UPDATE ca_cities SET
  static_title   = 'Lost & Found in Vancouver: Report a Lost Item',
  static_content = 'Lost something in Vancouver? Report it in minutes and we route it to the right VPD station, TransLink (SkyTrain/bus/SeaBus), rideshare and Vancouver (YVR) lost & found, plus local groups.'
WHERE province_id = 'BC' AND city_ascii = 'vancouver';

-- ============================================================
-- IMPORT LONG-TAIL (le reste des villes, comme la base US)
-- Source recommandée : SimpleMaps "Canada Cities Database" (Basic = gratuit, CC-BY 4.0).
--   colonnes utiles : city, city_ascii, province_id, province_name, lat, lng, population, timezone
-- Étapes :
--   1) Télécharger canadacities.csv depuis simplemaps.com/data/canada-cities
--   2) Table Editor Supabase → ca_cities → Import CSV → mapper les colonnes ci-dessus
--   3) (option) filtrer population > 10 000 pour démarrer léger
-- Vérif : SELECT province_id, count(*) FROM ca_cities GROUP BY 1 ORDER BY 2 DESC;
-- ============================================================
