-- ============================================================
-- Case inbox v2 : suivi des établissements contactés par dossier
-- À exécuter une fois dans le SQL editor de Supabase.
-- ============================================================

CREATE TABLE IF NOT EXISTS case_establishments (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lost_item_id    text        NOT NULL,          -- lost_items.id
  name            text        NOT NULL,          -- ex: "JFK Lost & Found"
  email           text,
  url             text,                          -- page ou formulaire de contact
  contacted_email boolean     NOT NULL DEFAULT false,
  contacted_form  boolean     NOT NULL DEFAULT false,
  notes           text,
  created_at      timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_case_establishments_item
  ON case_establishments (lost_item_id, created_at DESC);

ALTER TABLE case_establishments ENABLE ROW LEVEL SECURITY;
