-- ============================================================
-- Case inbox : toutes les conversations groupées par signalement
-- À exécuter une fois dans le SQL editor de Supabase.
-- ============================================================

CREATE TABLE IF NOT EXISTS case_messages (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lost_item_id  text        NOT NULL,            -- lost_items.id
  public_id     text,                            -- lost_items.public_id (5 chiffres), redondance pratique
  direction     text        NOT NULL,            -- 'in' (reçu) | 'out' (envoyé)
  from_email    text,
  to_email      text,
  subject       text,
  body_text     text,
  body_html     text,
  meta          jsonb,                           -- brut Mailgun / infos d'envoi
  created_at    timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_case_messages_item
  ON case_messages (lost_item_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_case_messages_public_id
  ON case_messages (public_id);
