-- ============================================================
-- Guides ville enrichis (générés avec validation manuelle)
-- À exécuter une fois dans le SQL editor de Supabase.
-- ============================================================

CREATE TABLE IF NOT EXISTS city_guides (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  state_id    text        NOT NULL,               -- "NJ"
  city_slug   text        NOT NULL,               -- city_ascii en minuscules, ex "belmar"
  guide       jsonb       NOT NULL,               -- objet CityGuide (lib/cityGuides.ts)
  status      text        NOT NULL DEFAULT 'draft',  -- 'draft' | 'published'
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now(),
  UNIQUE (state_id, city_slug)
);

CREATE INDEX IF NOT EXISTS idx_city_guides_published
  ON city_guides (state_id, city_slug) WHERE status = 'published';

ALTER TABLE city_guides ENABLE ROW LEVEL SECURITY;
