-- Compteurs d'usage anonymes (ex: téléchargements du générateur d'affiche).
-- Aucune donnée personnelle : juste le nom de l'événement et l'horodatage.
-- À exécuter une fois dans le SQL editor de Supabase.

CREATE TABLE IF NOT EXISTS events (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event      text        NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_events_event_date ON events (event, created_at DESC);

ALTER TABLE events ENABLE ROW LEVEL SECURITY;
