-- ============================================================
-- Match-watch : veille automatique des objets perdus
-- À exécuter une fois dans le SQL editor de Supabase.
-- ============================================================

-- 1) Colonnes de cadence sur les signalements
ALTER TABLE lost_items
  ADD COLUMN IF NOT EXISTS search_status  text        NOT NULL DEFAULT 'active',   -- 'active' | 'done'
  ADD COLUMN IF NOT EXISTS next_search_at timestamptz,                              -- prochain passage prévu
  ADD COLUMN IF NOT EXISTS last_searched_at timestamptz;

-- Amorce : tout signalement actif est éligible tout de suite
UPDATE lost_items
SET next_search_at = COALESCE(next_search_at, now())
WHERE search_status = 'active' AND next_search_at IS NULL;

-- Index pour sélectionner rapidement les signalements « dus »
CREATE INDEX IF NOT EXISTS idx_lost_items_next_search
  ON lost_items (next_search_at)
  WHERE search_status = 'active';

-- 2) Candidats de match trouvés en ligne (anti-doublon par URL / signalement)
CREATE TABLE IF NOT EXISTS match_candidates (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lost_item_id text        NOT NULL,
  url          text        NOT NULL,
  title        text,
  snippet      text,
  source       text,                       -- 'web' | 'facebook' | 'reddit' ...
  verdict      text,                        -- 'yes' | 'maybe' | 'no'
  confidence   int,
  reason       text,
  emailed      boolean     NOT NULL DEFAULT false,
  created_at   timestamptz NOT NULL DEFAULT now(),
  UNIQUE (lost_item_id, url)
);

CREATE INDEX IF NOT EXISTS idx_match_candidates_unemailed
  ON match_candidates (emailed) WHERE emailed = false;
