-- 🔗 Rapprochement inventaire établissement ↔ déclarations de perte.
-- À exécuter une fois dans le SQL editor de Supabase.
--
-- Principe : un candidat = un couple (déclaration de perte, objet trouvé).
-- Le score vient du moteur déterministe (lib/orgMatch.ts), gratuit. L'étage IA
-- est optionnel et n'écrit que dans ai_verdict / ai_reason.
--
-- Le bureau de l'établissement voit les candidats et tranche ; le propriétaire
-- n'est prévenu qu'après confirmation humaine. C'est ce qui évite d'envoyer de
-- faux espoirs, et ce qui garde le volume d'e-mails bas.

CREATE TABLE IF NOT EXISTS org_matches (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lost_item_id   text        NOT NULL,
  found_item_id  text        NOT NULL,
  org_id         uuid        REFERENCES organizations(id) ON DELETE CASCADE,

  score          int         NOT NULL,             -- 0-100, moteur déterministe
  level          text        NOT NULL,             -- 'strong' | 'possible'
  reasons        text[]      NOT NULL DEFAULT '{}',

  ai_verdict     text,                             -- 'yes' | 'maybe' | 'no' | null
  ai_confidence  int,
  ai_reason      text,

  status         text        NOT NULL DEFAULT 'new', -- new | dismissed | confirmed | returned
  handled_by     text,
  handled_at     timestamptz,

  notified_org_at   timestamptz,
  notified_owner_at timestamptz,

  created_at     timestamptz NOT NULL DEFAULT now(),
  UNIQUE (lost_item_id, found_item_id)
);

CREATE INDEX IF NOT EXISTS org_matches_org_new_idx
  ON org_matches (org_id, status) WHERE status = 'new';
CREATE INDEX IF NOT EXISTS org_matches_lost_idx  ON org_matches (lost_item_id);
CREATE INDEX IF NOT EXISTS org_matches_found_idx ON org_matches (found_item_id);

-- Interrupteur IA par organisation. Le rapprochement déterministe tourne
-- toujours ; celui-ci n'ajoute que l'avis du modèle, et seulement si la
-- variable d'environnement ORG_MATCH_AI est également active.
ALTER TABLE organizations
  ADD COLUMN IF NOT EXISTS match_ai boolean NOT NULL DEFAULT false;
