-- org-portal-complet.sql
--
-- TOUTES les migrations du portail établissements, dans l'ordre, en un seul
-- fichier. Chaque instruction est relançable (IF NOT EXISTS, CREATE OR
-- REPLACE, DROP ... IF EXISTS) : ce qui existe déjà est laissé tel quel, ce
-- qui manque est créé. Aucune donnée n'est supprimée.
--
-- À coller tel quel dans le SQL Editor de Supabase, AVANT de déployer.


-- ════════════════════════════════════════════════════════════════════
-- org-portal-supabase.sql
-- ════════════════════════════════════════════════════════════════════

-- 🏛️ Portail établissements (phase 1a) : organisations, membres, extension
-- de found_items (inventaire), journal d'audit.
-- À exécuter une fois dans le SQL editor de Supabase.

CREATE TABLE IF NOT EXISTS organizations (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  slug text UNIQUE NOT NULL,
  name text NOT NULL,
  type text NOT NULL DEFAULT 'other',          -- police | city | university | hotel | transit | other
  state_id text,
  city text,
  public_email text,
  phone text,
  verified boolean NOT NULL DEFAULT false,     -- page publique visible après validation Anna
  plan text NOT NULL DEFAULT 'free',
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS org_members (
  org_id uuid REFERENCES organizations(id) ON DELETE CASCADE,
  user_id uuid NOT NULL,                       -- auth.users.id
  role text NOT NULL DEFAULT 'admin',          -- admin | staff
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (org_id, user_id)
);

-- Inventaire : les objets des établissements vivent dans found_items
-- (même monde que les dépôts publics, même matching plus tard)
ALTER TABLE found_items
  ADD COLUMN IF NOT EXISTS org_id uuid REFERENCES organizations(id),
  ADD COLUMN IF NOT EXISTS org_ref text,               -- F-0001 par organisation
  ADD COLUMN IF NOT EXISTS storage_location text,      -- étagère B3, casier A1...
  ADD COLUMN IF NOT EXISTS status text DEFAULT 'stored', -- stored | claim_pending | returned | disposed
  ADD COLUMN IF NOT EXISTS legal_deadline date,
  ADD COLUMN IF NOT EXISTS returned_at timestamptz;

CREATE INDEX IF NOT EXISTS found_items_org_idx ON found_items(org_id);

-- Journal d'audit (registre légal automatique)
CREATE TABLE IF NOT EXISTS org_item_events (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  org_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  item_id text NOT NULL,
  type text NOT NULL,          -- created | claim_received | proof_ok | returned | disposed | note
  note text,
  actor_email text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS org_item_events_item_idx ON org_item_events(item_id);


-- ════════════════════════════════════════════════════════════════════
-- org-portal-1b.sql
-- ════════════════════════════════════════════════════════════════════

-- 🏛️ Portail établissements phase 1b : visibilité publique contrôlée.
-- À exécuter une fois dans le SQL editor de Supabase.

-- Interrupteur global de la page publique (choix de l'établissement)
ALTER TABLE organizations
  ADD COLUMN IF NOT EXISTS public_listing boolean NOT NULL DEFAULT true;

-- Par objet : visible publiquement ? + libellé public générique
-- (la description détaillée et la photo ne sortent JAMAIS publiquement :
--  elles servent de preuve de propriété lors des réclamations)
ALTER TABLE found_items
  ADD COLUMN IF NOT EXISTS public_visible boolean NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS public_label text;


-- ════════════════════════════════════════════════════════════════════
-- org-matches.sql
-- ════════════════════════════════════════════════════════════════════

-- 🔗 Rapprochement inventaire établissement ↔ déclarations de perte.
-- À exécuter une fois dans le SQL editor de Supabase.
--
-- Principe : un candidat = un couple (déclaration de perte, objet trouvé).
-- Le score vient du moteur déterministe (lib/orgMatch.ts), gratuit. L'étage IA
-- est optionnel et n'écrit que dans ai_verdict / ai_reason.
--
-- Le bureau de l'établissement voit les candidats et tranche ; le propriétaire
-- n'est prévenu qu'après confirmation humaine. C'est ce qui évite d'envoyer de
-- faux espoirs, et ce qui garde le volume d'e-mails bas.

CREATE TABLE IF NOT EXISTS org_matches (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lost_item_id   text        NOT NULL,
  found_item_id  text        NOT NULL,
  org_id         uuid        REFERENCES organizations(id) ON DELETE CASCADE,

  score          int         NOT NULL,             -- 0-100, moteur déterministe
  level          text        NOT NULL,             -- 'strong' | 'possible'
  reasons        text[]      NOT NULL DEFAULT '{}',

  ai_verdict     text,                             -- 'yes' | 'maybe' | 'no' | null
  ai_confidence  int,
  ai_reason      text,

  status         text        NOT NULL DEFAULT 'new', -- new | dismissed | confirmed | returned
  handled_by     text,
  handled_at     timestamptz,

  notified_org_at   timestamptz,
  notified_owner_at timestamptz,

  created_at     timestamptz NOT NULL DEFAULT now(),
  UNIQUE (lost_item_id, found_item_id)
);

CREATE INDEX IF NOT EXISTS org_matches_org_new_idx
  ON org_matches (org_id, status) WHERE status = 'new';
CREATE INDEX IF NOT EXISTS org_matches_lost_idx  ON org_matches (lost_item_id);
CREATE INDEX IF NOT EXISTS org_matches_found_idx ON org_matches (found_item_id);

-- Interrupteur IA par organisation. Le rapprochement déterministe tourne
-- toujours ; celui-ci n'ajoute que l'avis du modèle, et seulement si la
-- variable d'environnement ORG_MATCH_AI est également active.
ALTER TABLE organizations
  ADD COLUMN IF NOT EXISTS match_ai boolean NOT NULL DEFAULT false;


-- ════════════════════════════════════════════════════════════════════
-- org-retention.sql
-- ════════════════════════════════════════════════════════════════════

-- org-retention.sql
--
-- Durée de conservation propre à l'établissement.
--
-- Jusqu'ici found_items.legal_deadline était calculé avec la loi de l'État,
-- qui encadre la garde PAR LES FORCES DE L'ORDRE. Juste pour un commissariat,
-- faux pour une université, un hôtel ou un aéroport : eux appliquent leur
-- propre politique.
--
-- NULL = « pas réglé ». Les commissariats et mairies restent alors sur la loi
-- de l'État, exactement comme aujourd'hui ; les autres passent sur un repli de
-- 30 jours affiché comme provisoire, à confirmer depuis le tableau de bord.
--
-- À exécuter AVANT de déployer.

alter table organizations
  add column if not exists retention_days integer;

alter table organizations
  add column if not exists retention_set_at timestamptz;

comment on column organizations.retention_days is
  'Durée de garde en jours, politique de l''établissement. NULL = non réglé (loi de l''État pour police/city, 30 jours provisoires sinon).';

alter table organizations
  drop constraint if exists organizations_retention_days_check;

alter table organizations
  add constraint organizations_retention_days_check
  check (retention_days is null or (retention_days between 1 and 3650));


-- ════════════════════════════════════════════════════════════════════
-- org-disposition.sql
-- ════════════════════════════════════════════════════════════════════

-- org-disposition.sql
--
-- Ce que l'objet est devenu, et quand — réellement.
--
-- legal_deadline n'est qu'une ÉLIGIBILITÉ : « à partir d'ici, vous avez le
-- droit de vous en séparer ». Un objet peut rester six mois sur l'étagère
-- après cette date. Rien ne doit donc se déclencher à l'échéance : les
-- horloges de suppression partent du départ réel de l'objet, consigné par un
-- agent.
--
-- À exécuter AVANT de déployer.

alter table found_items add column if not exists disposition text;
alter table found_items add column if not exists disposed_at timestamptz;
alter table found_items add column if not exists disposed_to text;
alter table found_items add column if not exists photo_purged_at timestamptz;

comment on column found_items.disposition is
  'Ce que l''objet est devenu : transferred_police | donated | discarded | returned_owner. NULL tant qu''il est au bureau.';
comment on column found_items.disposed_to is
  'À qui, en clair — « Sandy Springs PD, PV 2026-1183 ». C''est cette ligne qu''on lit à quelqu''un qui se manifeste huit mois plus tard.';
comment on column found_items.photo_purged_at is
  'Date de suppression de la photo. La fiche, elle, reste consultable.';

alter table found_items drop constraint if exists found_items_disposition_check;
alter table found_items add constraint found_items_disposition_check
  check (disposition is null or disposition in
    ('transferred_police','donated','discarded','returned_owner'));

-- Les deux balayages de maintenance filtrent là-dessus.
create index if not exists found_items_disposed_at_idx on found_items (disposed_at);


-- ════════════════════════════════════════════════════════════════════
-- org-ai-quota.sql
-- ════════════════════════════════════════════════════════════════════

-- org-ai-quota.sql
--
-- Plafond mensuel du scan par photo (le seul appel payant du portail,
-- ~1 centime par objet). Sans plafond, un bureau qui photographie tout son
-- stock, ou un script maladroit, transforme un outil offert en facture ouverte.
--
-- Le compteur est incrémenté et testé DANS LA MÊME transaction : deux agents
-- qui scannent en même temps ne peuvent pas passer tous les deux au-delà.
--
-- organizations.ai_quota permet de relever le plafond établissement par
-- établissement — c'est la marche payante : on vend un quota, pas un outil.
--
-- À exécuter AVANT de déployer.

create table if not exists org_ai_usage (
  org_id uuid not null references organizations(id) on delete cascade,
  month  text not null,                 -- 'YYYY-MM', en UTC
  used   integer not null default 0,
  primary key (org_id, month)
);

alter table organizations
  add column if not exists ai_quota integer;

comment on column organizations.ai_quota is
  'Plafond mensuel de scans photo. NULL = plafond par défaut du site.';

-- Consomme un scan si le quota le permet. Renvoie l''état après opération.
create or replace function org_ai_consume(p_org uuid, p_limit integer)
returns table(allowed boolean, used integer, quota integer)
language plpgsql
as $$
declare
  v_month text := to_char(now() at time zone 'utc', 'YYYY-MM');
  v_quota integer;
  v_used  integer;
begin
  select coalesce(o.ai_quota, p_limit) into v_quota
  from organizations o where o.id = p_org;
  if v_quota is null then v_quota := p_limit; end if;

  insert into org_ai_usage (org_id, month, used)
  values (p_org, v_month, 0)
  on conflict (org_id, month) do nothing;

  -- Verrou de ligne : la lecture et l''écriture ne peuvent pas être entrelacées.
  select u.used into v_used
  from org_ai_usage u
  where u.org_id = p_org and u.month = v_month
  for update;

  if v_used >= v_quota then
    return query select false, v_used, v_quota;
    return;
  end if;

  update org_ai_usage u set used = u.used + 1
  where u.org_id = p_org and u.month = v_month
  returning u.used into v_used;

  return query select true, v_used, v_quota;
end;
$$;

-- Rend le scan décompté quand l''appel a échoué : on ne facture pas un raté.
create or replace function org_ai_refund(p_org uuid)
returns void
language sql
as $$
  update org_ai_usage
  set used = greatest(used - 1, 0)
  where org_id = p_org
    and month = to_char(now() at time zone 'utc', 'YYYY-MM');
$$;


-- ════════════════════════════════════════════════════════════════════
-- org-portal-2.sql
-- ════════════════════════════════════════════════════════════════════

-- org-portal-2.sql
--
-- Portail établissements, lot 2 :
--   1. échéances de garde : affichage activable par établissement
--   2. références F-#### attribuées par un compteur atomique (plus de doublon
--      quand deux agents enregistrent en même temps, ni après une suppression)
--   3. dépôts par QR code : la personne qui trouve l'objet le décrit elle-même,
--      l'accueil confirme à la remise
--   4. invitations de collègues
--   5. verrouillage : tables du portail fermées à la clé publique, fonctions
--      réservées au serveur
--
-- À exécuter AVANT de déployer. Relançable sans risque.

-- ── 1. Échéances ────────────────────────────────────────────────────────────
alter table organizations
  add column if not exists deadline_tracking boolean;

comment on column organizations.deadline_tracking is
  'Affichage des échéances de garde dans le tableau de bord. NULL = défaut du type (police / city : oui, autres : non).';

-- ── 2. Références ───────────────────────────────────────────────────────────
alter table organizations
  add column if not exists ref_seq integer not null default 0;

-- Reprise de l''existant : le compteur repart du plus grand numéro déjà émis.
update organizations o
set ref_seq = greatest(
  o.ref_seq,
  coalesce((
    select max((substring(f.org_ref from '^F-(\d+)$'))::integer)
    from found_items f
    where f.org_id = o.id
  ), 0),
  (select count(*) from found_items f where f.org_id = o.id)::integer
);

-- Réserve p_n numéros d''un coup et renvoie le DERNIER. Un import de 300
-- lignes réserve 300 numéros en une seule écriture.
create or replace function org_next_ref(p_org uuid, p_n integer default 1)
returns integer
language sql
as $$
  update organizations
  set ref_seq = ref_seq + greatest(coalesce(p_n, 1), 1)
  where id = p_org
  returning ref_seq;
$$;

-- ── 3. Dépôts par QR code ───────────────────────────────────────────────────
-- Table à part, volontairement : tant que l''accueil n''a pas l''objet en main,
-- ce n''est pas de l''inventaire. Rien de ce qui lit found_items (page publique,
-- rapprochement, pages villes) ne peut donc voir un dépôt non confirmé.
create table if not exists org_intakes (
  id uuid primary key default gen_random_uuid(),
  org_id uuid not null references organizations(id) on delete cascade,
  code text not null,                       -- code court montré à l''accueil
  title text not null,
  description text,
  found_location text,
  found_at date not null,
  photo_url text,
  finder_name text,
  finder_email text,
  status text not null default 'pending',   -- pending | confirmed | rejected
  item_id text,                             -- found_items.id une fois confirmé
  created_at timestamptz not null default now(),
  resolved_at timestamptz
);

create index if not exists org_intakes_org_status_idx on org_intakes (org_id, status);
create index if not exists org_intakes_created_idx on org_intakes (created_at);

alter table found_items
  add column if not exists intake_id uuid;

comment on column found_items.intake_id is
  'Dépôt par QR code à l''origine de la fiche, s''il y en a un.';

-- ── 4. Invitations ──────────────────────────────────────────────────────────
create table if not exists org_invites (
  id uuid primary key default gen_random_uuid(),
  org_id uuid not null references organizations(id) on delete cascade,
  email text not null,
  role text not null default 'staff',       -- admin | staff
  token text not null unique,
  invited_by text,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null default (now() + interval '14 days'),
  accepted_at timestamptz
);

create index if not exists org_invites_org_idx on org_invites (org_id);

-- ── 5. Verrouillage ─────────────────────────────────────────────────────────
-- Toutes ces tables ne sont lues que par les routes serveur (clé service_role,
-- qui ignore la RLS). RLS activée sans aucune policy = la clé publique du site
-- ne peut ni les lire ni les écrire.
alter table organizations   enable row level security;
alter table org_members     enable row level security;
alter table org_item_events enable row level security;
alter table org_ai_usage    enable row level security;
alter table org_matches     enable row level security;
alter table org_intakes     enable row level security;
alter table org_invites     enable row level security;

-- Par défaut, Supabase expose toute fonction à la clé publique : n''importe qui
-- pouvait appeler org_ai_refund en boucle pour remettre un quota à zéro.
revoke execute on function org_next_ref(uuid, integer)   from public, anon, authenticated;
revoke execute on function org_ai_consume(uuid, integer) from public, anon, authenticated;
revoke execute on function org_ai_refund(uuid)           from public, anon, authenticated;
grant  execute on function org_next_ref(uuid, integer)   to service_role;
grant  execute on function org_ai_consume(uuid, integer) to service_role;
grant  execute on function org_ai_refund(uuid)           to service_role;


-- ════════════════════════════════════════════════════════════════════
-- org-portal-3.sql
-- ════════════════════════════════════════════════════════════════════

-- org-portal-3.sql
--
-- Signalements « gardés par la personne qui a trouvé l'objet ».
-- Quelqu'un trouve un objet sur le campus, ne le dépose pas à l'accueil, mais
-- laisse son e-mail pour que le propriétaire puisse le récupérer auprès de lui.
-- L'établissement ne stocke rien : il sait où est l'objet et met en relation,
-- après avoir vérifié la preuve de propriété.
--
-- À exécuter APRÈS org-portal-2.sql et AVANT de déployer. Relançable sans risque.

alter table org_intakes
  add column if not exists held_by text not null default 'desk';      -- desk | finder

alter table org_intakes drop constraint if exists org_intakes_held_by_check;
alter table org_intakes add constraint org_intakes_held_by_check
  check (held_by in ('desk', 'finder'));

-- Visibilité sur la page publique : JAMAIS automatique. Un formulaire public
-- ne doit pas pouvoir alimenter une page publique sans qu'un agent l'ait vu.
alter table org_intakes
  add column if not exists public_visible boolean not null default false,
  add column if not exists public_label text;

comment on column org_intakes.held_by is
  'desk = sera remis à l''accueil (code de dépôt) ; finder = gardé par la personne qui l''a trouvé, joignable par e-mail.';

create index if not exists org_intakes_public_idx
  on org_intakes (org_id, held_by, public_visible);

-- L'établissement choisit s'il accepte ce type de signalement.
alter table organizations
  add column if not exists finder_held_enabled boolean not null default true;

comment on column organizations.finder_held_enabled is
  'Si faux, le formulaire « Found something? » ne propose que la remise à l''accueil.';

